apiVersion: v1
kind: Service
metadata:
  name: {{ include "orida.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "orida.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: backend
    {{- include "orida.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
