apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orida.fullname" . }}-backend-cookie
  labels:
    app.kubernetes.io/component: backend
    {{- include "orida.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.backend.cookie.secret | quote }}
