apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orida.fullname" . }}-backend-migrate
  labels:
    app.kubernetes.io/component: backend
    {{- include "orida.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: '-1'
type: Opaque
stringData:
  url: postgresql://{{ .Values.backend.database.user }}:{{ .Values.backend.database.password | urlquery }}@{{ .Values.backend.database.host }}:{{ .Values.backend.database.port }}/{{ .Values.backend.database.name }}
