{{ if .Values.basic_auth_password }}
apiVersion: v1
stringData:
  auth: {{ htpasswd "orida" .Values.basic_auth_password }}
kind: Secret
metadata:
  name: {{ include "orida.fullname" . }}-basic-auth
type: Opaque
{{ end }}
